"""
V2 Evidence schema — EvidenceChunk.

EvidenceChunk is the fundamental unit of the Vector Evidence Store.
Each chunk has a type, is linked to a document and section, and stores
the original text content that can be retrieved for citation and grounding.
"""

from __future__ import annotations

import hashlib
import json
from typing import Any

from pydantic import BaseModel, Field, field_validator


# Allowed chunk types for V2 evidence store
ALLOWED_CHUNK_TYPES = {
    "summary",     # Document or section summary (generated by LLM)
    "section",     # Full section content
    "small",       # Standard small text chunk (1500 chars)
    "table",       # Table content (markdown or structured)
    "code",        # Source code block
    "sql",         # SQL statement or DDL
    "api",         # API documentation block
    "config",      # Configuration file content
    "testcase",    # Test case content
    "operation",   # Operation/procedure documentation
}


class EvidenceChunk(BaseModel):
    """Represents a single evidence chunk in the Vector Evidence Store.

    Evidence chunks are the base unit for:
    - Semantic retrieval (vector search)
    - Citation/grounding for graph nodes and edges
    - Original text evidence for answers

    Every graph node and edge should link back to one or more EvidenceChunks
    via evidence_chunk_ids.
    """

    chunk_id: str = Field(..., description="Unique chunk identifier")
    document_id: str = Field(..., description="Parent document identifier")
    section_id: str | None = Field(default=None, description="Parent section identifier (None for doc-level chunks)")
    project: str = Field(default="murata", description="Project name")
    dataset: str = Field(default="murata", description="Dataset name")
    run_id: str = Field(default="murata_semantic_v2", description="Run identifier")
    doc_type: str = Field(default="unknown", description="Document type of source")
    chunk_type: str = Field(..., description="Chunk type: summary, section, small, table, code, sql, api, config, testcase, operation")
    title: str = Field(default="", description="Chunk title or heading")
    text: str = Field(default="", description="Chunk text content")
    heading_path: list[str] = Field(default_factory=list, description="Hierarchical heading path")
    source_path: str = Field(default="", description="S3 key or local path of source document")
    language: str = Field(default="auto", description="Language: ja, zh, en, mixed, or auto")
    metadata: dict[str, Any] = Field(default_factory=dict, description="Flexible metadata")

    @field_validator("chunk_id")
    @classmethod
    def validate_chunk_id(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError("chunk_id must not be empty")
        return v.strip()

    @field_validator("chunk_type")
    @classmethod
    def validate_chunk_type(cls, v: str) -> str:
        if v not in ALLOWED_CHUNK_TYPES:
            raise ValueError(
                f"chunk_type '{v}' is not allowed. "
                f"Allowed types: {sorted(ALLOWED_CHUNK_TYPES)}"
            )
        return v

    @field_validator("text")
    @classmethod
    def validate_text(cls, v: str) -> str:
        if not v or not v.strip():
            raise ValueError("text must not be empty — evidence chunks must contain content")
        return v

    @staticmethod
    def generate_id(
        document_id: str,
        section_id: str | None,
        chunk_index: int,
        content_hash: str | None = None,
    ) -> str:
        """Generate a deterministic chunk_id.

        Args:
            document_id: Parent document ID
            section_id: Parent section ID (or None)
            chunk_index: Index of this chunk within the section/document
            content_hash: Optional hash of content for uniqueness
        """
        parts = f"{document_id}:{section_id or 'none'}:{chunk_index}"
        if content_hash:
            parts += f":{content_hash}"
        return hashlib.sha256(parts.encode("utf-8")).hexdigest()[:16]

    @staticmethod
    def content_hash(text: str) -> str:
        """Generate a short hash of text content for deduplication."""
        return hashlib.sha256(text.encode("utf-8")).hexdigest()[:8]

    def to_jsonl(self) -> str:
        """Serialize to a single JSONL line."""
        return json.dumps(self.model_dump(), ensure_ascii=False)

    @classmethod
    def from_jsonl(cls, line: str) -> "EvidenceChunk":
        """Deserialize from a single JSONL line."""
        return cls.model_validate_json(line.strip())
