"""Static validation tests for UnifiedOutputWriter and unified parsing structure.

Validates:
1. UnifiedOutputWriter creates expected canonical paths for arbitrary project/workbook names
2. No sample-specific hardcoding in output_writer.py
3. Frontmatter contains all required downstream fields
4. parsing_manifest.json is generated by the dualrag parse command
5. legacy_compat is separate from canonical parsed/evidence output
6. Japanese project names and special characters handled safely
7. Official production entrypoint (dualrag parse) uses UnifiedOutputWriter
"""

import importlib
import inspect
import json
import os
import re
import sys
import tempfile
from pathlib import Path
from unittest.mock import patch

import pytest


# ─────────────────────────────────────────────────────────────────────────────
# Test 1: UnifiedOutputWriter creates expected canonical paths
# ─────────────────────────────────────────────────────────────────────────────


class TestUnifiedOutputWriterPaths:
    def test_canonical_directory_structure(self, tmp_path):
        """UnifiedOutputWriter creates parsed/, evidence/, legacy_compat/ under run_dir."""
        from hermes_bedrock_agent.parsing.output_writer import UnifiedOutputWriter

        run_dir = tmp_path / "run_20260612_120000"
        run_dir.mkdir()
        writer = UnifiedOutputWriter(run_dir, "test_project_123")

        # setup_workbook should create staging + canonical dirs
        wb_paths = writer.setup_workbook("TestWorkbook")

        # Check that canonical paths are under the right structure
        assert wb_paths.parsed_dir == run_dir / "parsed" / "excel" / "TestWorkbook"
        assert wb_paths.evidence_dir == run_dir / "evidence" / "excel" / "TestWorkbook"
        assert wb_paths.legacy_dir == run_dir / "legacy_compat" / "TestWorkbook"

    def test_japanese_workbook_name(self, tmp_path):
        """Japanese workbook names are handled without crashing."""
        from hermes_bedrock_agent.parsing.output_writer import UnifiedOutputWriter

        run_dir = tmp_path / "run_20260612_120000"
        run_dir.mkdir()
        writer = UnifiedOutputWriter(run_dir, "14_債務奉行クラウド")

        wb_paths = writer.setup_workbook("MW_IFマッピング表_v5.2")

        # Paths should be created without error
        assert wb_paths.parsed_dir.exists()
        assert wb_paths.evidence_dir.exists()
        assert "MW_IFマッピング表_v5.2" in str(wb_paths.parsed_dir)

    def test_spaces_in_workbook_name(self, tmp_path):
        """Workbook names with spaces work correctly."""
        from hermes_bedrock_agent.parsing.output_writer import UnifiedOutputWriter

        run_dir = tmp_path / "run_test"
        run_dir.mkdir()
        writer = UnifiedOutputWriter(run_dir, "my project")

        wb_paths = writer.setup_workbook("Sales Report 2025")
        assert wb_paths.parsed_dir.exists()
        assert "Sales Report 2025" in str(wb_paths.parsed_dir)

    def test_multiple_workbooks(self, tmp_path):
        """Multiple workbooks create separate subdirectories."""
        from hermes_bedrock_agent.parsing.output_writer import UnifiedOutputWriter

        run_dir = tmp_path / "run_test"
        run_dir.mkdir()
        writer = UnifiedOutputWriter(run_dir, "multi_wb_project")

        wb1 = writer.setup_workbook("WorkbookA")
        wb2 = writer.setup_workbook("WorkbookB")
        wb3 = writer.setup_workbook("マスタ定義書")

        assert wb1.parsed_dir != wb2.parsed_dir
        assert wb2.parsed_dir != wb3.parsed_dir
        assert wb1.parsed_dir.exists()
        assert wb2.parsed_dir.exists()
        assert wb3.parsed_dir.exists()

    def test_project_id_stored(self, tmp_path):
        """Project ID is stored and accessible."""
        from hermes_bedrock_agent.parsing.output_writer import UnifiedOutputWriter

        run_dir = tmp_path / "run_test"
        run_dir.mkdir()
        writer = UnifiedOutputWriter(run_dir, "my_project_id")
        assert writer.project_id == "my_project_id"


# ─────────────────────────────────────────────────────────────────────────────
# Test 2: No sample-specific hardcoding
# ─────────────────────────────────────────────────────────────────────────────


class TestNoHardcoding:
    def test_no_sample_20260519_in_output_writer(self):
        """output_writer.py must not contain hardcoded sample references."""
        src_path = Path(__file__).resolve().parent.parent / "src" / "hermes_bedrock_agent" / "parsing" / "output_writer.py"
        content = src_path.read_text(encoding="utf-8")

        forbidden = ["sample_20260519", "サンプル20260519", "s3-hulftchina-rd"]
        for term in forbidden:
            assert term not in content, f"Hardcoded reference found: {term}"

    def test_no_hardcoded_project_names_in_output_writer(self):
        """output_writer.py should not reference specific project names."""
        src_path = Path(__file__).resolve().parent.parent / "src" / "hermes_bedrock_agent" / "parsing" / "output_writer.py"
        content = src_path.read_text(encoding="utf-8")

        # Specific known project names that should NOT appear
        forbidden = ["saimu_bugyo", "yangma", "murata"]
        for term in forbidden:
            assert term not in content, f"Project-specific name found: {term}"


# ─────────────────────────────────────────────────────────────────────────────
# Test 3: Frontmatter contains all required downstream fields
# ─────────────────────────────────────────────────────────────────────────────


class TestFrontmatterContract:
    """Validate that UnifiedOutputWriter frontmatter includes all fields
    required by the chunker and graph scanner downstream."""

    REQUIRED_BY_CHUNKER = {"source_file", "source_type", "parser_type", "document_role"}
    REQUIRED_BY_GRAPH_SCANNER = {"source_file", "source_type", "parser_type", "document_role"}
    REQUIRED_BY_BUILD_KB = {"project_id"}
    # Union of all downstream requirements
    ALL_REQUIRED = REQUIRED_BY_CHUNKER | REQUIRED_BY_GRAPH_SCANNER | REQUIRED_BY_BUILD_KB

    def _get_frontmatter_fields(self) -> set:
        """Extract frontmatter field names from _build_frontmatter output."""
        from hermes_bedrock_agent.parsing.output_writer import UnifiedOutputWriter

        with tempfile.TemporaryDirectory() as tmpdir:
            run_dir = Path(tmpdir) / "run"
            run_dir.mkdir()
            writer = UnifiedOutputWriter(run_dir, "test_project")
            fm_text = writer._build_frontmatter(
                source_file="test.xlsx",
                workbook_name="TestWB",
                sheet_index=0,
                sheet_name="sheet_00",
                evidence_path="evidence/excel/TestWB/sheet_00/",
            )

        # Parse the YAML frontmatter
        lines = fm_text.strip().split("\n")
        assert lines[0] == "---"
        assert lines[-1] == "---"

        fields = set()
        for line in lines[1:-1]:
            if ":" in line:
                key = line.split(":", 1)[0].strip()
                fields.add(key)
        return fields

    def test_chunker_fields_present(self):
        """All fields read by chunker.py are present in frontmatter."""
        fields = self._get_frontmatter_fields()
        missing = self.REQUIRED_BY_CHUNKER - fields
        assert not missing, f"Missing fields required by chunker: {missing}"

    def test_graph_scanner_fields_present(self):
        """All fields read by graph_pipeline/scanner.py are present in frontmatter."""
        fields = self._get_frontmatter_fields()
        missing = self.REQUIRED_BY_GRAPH_SCANNER - fields
        assert not missing, f"Missing fields required by graph scanner: {missing}"

    def test_project_id_field_present(self):
        """project_id is present for build-kb isolation."""
        fields = self._get_frontmatter_fields()
        assert "project_id" in fields

    def test_all_required_fields_present(self):
        """Union of all downstream requirements is satisfied."""
        fields = self._get_frontmatter_fields()
        missing = self.ALL_REQUIRED - fields
        assert not missing, f"Missing required fields: {missing}"

    def test_frontmatter_values_not_empty(self):
        """Frontmatter values are non-empty strings."""
        from hermes_bedrock_agent.parsing.output_writer import UnifiedOutputWriter

        with tempfile.TemporaryDirectory() as tmpdir:
            run_dir = Path(tmpdir) / "run"
            run_dir.mkdir()
            writer = UnifiedOutputWriter(run_dir, "test_project")
            fm_text = writer._build_frontmatter(
                source_file="s3://bucket/data.xlsx",
                workbook_name="TestWB",
                sheet_index=3,
                sheet_name="sheet_03",
                evidence_path="evidence/excel/TestWB/sheet_03/",
            )

        # Check key fields have non-empty values
        assert 'source_file: "s3://bucket/data.xlsx"' in fm_text
        assert 'project_id: "test_project"' in fm_text
        assert 'source_type: "excel"' in fm_text
        assert 'parser_type: "excel_vlm"' in fm_text
        assert 'document_role: "data_source"' in fm_text

    def test_additional_useful_fields(self):
        """Extra useful fields (not strictly required) are present."""
        fields = self._get_frontmatter_fields()
        useful = {"workbook_name", "sheet_index", "sheet_name", "parsed_at", "evidence_path"}
        for f in useful:
            assert f in fields, f"Useful field '{f}' missing from frontmatter"

    def test_extended_document_fields(self):
        """New document metadata fields are present for future consumers."""
        fields = self._get_frontmatter_fields()
        extended = {
            "document_type", "document_id", "document_name",
            "original_relative_path", "display_name", "evidence_paths",
        }
        for f in extended:
            assert f in fields, f"Extended field '{f}' missing from frontmatter"

    def test_document_id_deterministic(self):
        """document_id is stable across multiple calls with same inputs."""
        from hermes_bedrock_agent.parsing.output_writer import UnifiedOutputWriter

        with tempfile.TemporaryDirectory() as tmpdir:
            run_dir = Path(tmpdir) / "run"
            run_dir.mkdir()
            writer = UnifiedOutputWriter(run_dir, "proj_abc")
            fm1 = writer._build_frontmatter(
                source_file="s3://bucket/test.xlsx",
                workbook_name="TestWB",
                sheet_index=0,
                sheet_name="sheet_00",
                evidence_path="evidence/excel/TestWB/sheet_00/",
            )
            fm2 = writer._build_frontmatter(
                source_file="s3://bucket/test.xlsx",
                workbook_name="TestWB",
                sheet_index=0,
                sheet_name="sheet_00",
                evidence_path="evidence/excel/TestWB/sheet_00/",
            )

        # Extract document_id from both
        import re
        ids = re.findall(r'document_id: "([^"]+)"', fm1 + fm2)
        assert len(ids) == 2
        assert ids[0] == ids[1], "document_id must be deterministic"
        assert len(ids[0]) == 16, "document_id should be 16-char hex"

    def test_original_relative_path_strips_s3_prefix(self):
        """original_relative_path strips s3://bucket/ to get relative path."""
        from hermes_bedrock_agent.parsing.output_writer import UnifiedOutputWriter

        with tempfile.TemporaryDirectory() as tmpdir:
            run_dir = Path(tmpdir) / "run"
            run_dir.mkdir()
            writer = UnifiedOutputWriter(run_dir, "test_proj")
            fm = writer._build_frontmatter(
                source_file="s3://my-bucket/path/to/workbook.xlsx",
                workbook_name="workbook",
                sheet_index=0,
                sheet_name="sheet_00",
                evidence_path="evidence/excel/workbook/sheet_00/",
            )

        assert 'original_relative_path: "path/to/workbook.xlsx"' in fm

    def test_display_name_combines_workbook_and_sheet(self):
        """display_name shows workbook / sheet for readability."""
        from hermes_bedrock_agent.parsing.output_writer import UnifiedOutputWriter

        with tempfile.TemporaryDirectory() as tmpdir:
            run_dir = Path(tmpdir) / "run"
            run_dir.mkdir()
            writer = UnifiedOutputWriter(run_dir, "test_proj")
            fm = writer._build_frontmatter(
                source_file="s3://bucket/test.xlsx",
                workbook_name="売上管理表",
                sheet_index=2,
                sheet_name="sheet_02",
                evidence_path="evidence/excel/売上管理表/sheet_02/",
            )

        assert 'display_name: "売上管理表 / sheet_02"' in fm


# ─────────────────────────────────────────────────────────────────────────────
# Test 4: parsing_manifest.json generation
# ─────────────────────────────────────────────────────────────────────────────


class TestParsingManifest:
    def test_manifest_json_has_version(self, tmp_path):
        """manifest.json from write_manifest() has version and structure fields."""
        from hermes_bedrock_agent.parsing.output_writer import UnifiedOutputWriter

        run_dir = tmp_path / "run_test"
        run_dir.mkdir()
        writer = UnifiedOutputWriter(run_dir, "manifest_test")
        manifest_path = writer.write_manifest()

        data = json.loads(manifest_path.read_text())
        assert data["version"] == "2.0"
        assert data["structure"] == "unified_v1"
        assert data["project_id"] == "manifest_test"
        assert "paths" in data
        assert data["paths"]["parsed"] == "parsed/"
        assert data["paths"]["parsed_excel"] == "parsed/excel/"
        assert data["paths"]["parsed_mermaid"] == "parsed/mermaid/"
        assert data["paths"]["evidence"] == "evidence/"
        assert data["paths"]["intermediates"] == "intermediates/"
        assert data["paths"]["intermediates_mermaid"] == "intermediates/mermaid/"
        assert "supported_parsed_types" in data
        assert "mermaid" in data["supported_parsed_types"]

    def test_cli_parse_generates_parsing_manifest(self):
        """Code review: dualrag parse writes parsing_manifest.json."""
        src_path = Path(__file__).resolve().parent.parent / "src" / "hermes_bedrock_agent" / "cli.py"
        content = src_path.read_text(encoding="utf-8")

        # Must contain parsing_manifest.json generation
        assert "parsing_manifest.json" in content, \
            "cli.py parse command must generate parsing_manifest.json"
        assert '"manifest_version": "2.1"' in content, \
            "parsing_manifest.json must have manifest_version 2.1"
        assert '"structure": "unified_v1"' in content, \
            "parsing_manifest.json must declare unified_v1 structure"

    def test_orchestrator_generates_parsing_manifest(self):
        """Code review: orchestrator's save_parsing_manifest writes parsing_manifest.json."""
        src_path = (
            Path(__file__).resolve().parent.parent
            / "src" / "hermes_bedrock_agent" / "parsing" / "orchestrator.py"
        )
        content = src_path.read_text(encoding="utf-8")
        assert 'output_dir / "parsing_manifest.json"' in content


# ─────────────────────────────────────────────────────────────────────────────
# Test 5: legacy_compat is separate from canonical output
# ─────────────────────────────────────────────────────────────────────────────


class TestLegacyCompatSeparation:
    def test_legacy_dir_not_under_parsed(self, tmp_path):
        """legacy_compat/ is a sibling of parsed/, not inside it."""
        from hermes_bedrock_agent.parsing.output_writer import UnifiedOutputWriter

        run_dir = tmp_path / "run_test"
        run_dir.mkdir()
        writer = UnifiedOutputWriter(run_dir, "test")
        wb_paths = writer.setup_workbook("WB1")

        # legacy_compat should be run_dir/legacy_compat/, not run_dir/parsed/legacy_compat/
        assert wb_paths.legacy_dir.parent.parent == run_dir
        assert wb_paths.legacy_dir.parent.name == "legacy_compat"
        assert "parsed" not in str(wb_paths.legacy_dir)

    def test_canonical_parsed_not_symlink(self, tmp_path):
        """Canonical parsed/ directory is a real directory, not a symlink."""
        from hermes_bedrock_agent.parsing.output_writer import UnifiedOutputWriter

        run_dir = tmp_path / "run_test"
        run_dir.mkdir()
        writer = UnifiedOutputWriter(run_dir, "test")
        wb_paths = writer.setup_workbook("WB1")

        assert wb_paths.parsed_dir.is_dir()
        assert not wb_paths.parsed_dir.is_symlink()


# ─────────────────────────────────────────────────────────────────────────────
# Test 6: Production entrypoint (dualrag parse) uses UnifiedOutputWriter
# ─────────────────────────────────────────────────────────────────────────────


class TestProductionEntrypointUsesWriter:
    def test_cli_parse_imports_unified_output_writer(self):
        """dualrag parse command imports and uses UnifiedOutputWriter."""
        src_path = Path(__file__).resolve().parent.parent / "src" / "hermes_bedrock_agent" / "cli.py"
        content = src_path.read_text(encoding="utf-8")

        # The import must be inside the parse function
        assert "from .parsing.output_writer import UnifiedOutputWriter" in content
        assert "writer = UnifiedOutputWriter(run_dir" in content

    def test_parse_unified_script_uses_writer(self):
        """scripts/parse_unified.py imports and uses UnifiedOutputWriter."""
        script_path = Path(__file__).resolve().parent.parent / "scripts" / "parse_unified.py"
        content = script_path.read_text(encoding="utf-8")

        assert "from hermes_bedrock_agent.parsing.output_writer import UnifiedOutputWriter" in content
        assert "writer = UnifiedOutputWriter(" in content

    def test_orchestrator_does_not_use_old_style(self):
        """Orchestrator's parsed/ output uses type-aware subdirectories (not old-style)."""
        src_path = (
            Path(__file__).resolve().parent.parent
            / "src" / "hermes_bedrock_agent" / "parsing" / "orchestrator.py"
        )
        content = src_path.read_text(encoding="utf-8")

        # The orchestrator creates parsed/<type_subdir>/<safe_name>.md
        assert "type_parsed_dir = parsed_dir / type_subdir" in content
        assert "output_path = type_parsed_dir /" in content

        # It does NOT write directly to <workbook_name>/vlm_parsed/
        assert "vlm_parsed" not in content


# ─────────────────────────────────────────────────────────────────────────────
# Test 7: Old-style output only in deprecated scripts
# ─────────────────────────────────────────────────────────────────────────────


class TestOldStyleOutputClassification:
    """Verify that old-style output (workbook/pdf/images/vlm_parsed/) only
    exists in deprecated/compatibility scripts, never in production code."""

    PRODUCTION_FILES = [
        "src/hermes_bedrock_agent/cli.py",
        "src/hermes_bedrock_agent/cli_project.py",
        "src/hermes_bedrock_agent/parsing/orchestrator.py",
        "src/hermes_bedrock_agent/parsing/output_writer.py",
    ]

    DEPRECATED_SCRIPTS = [
        "scripts/_archive/parse_with_adapter.py",
        "scripts/_archive/run_parse_sys.py",
        "scripts/_archive/rerun_pipeline_sample_20260529.py",
    ]

    # Scripts that delegate to production code (not themselves old-style)
    WRAPPER_SCRIPTS = [
        "scripts/run_parse_system_python.py",  # Thin wrapper → dualrag parse (uses UnifiedOutputWriter)
    ]

    def test_production_files_no_old_style_canonical_output(self):
        """Production source files do not create old-style canonical output."""
        project_root = Path(__file__).resolve().parent.parent

        for rel_path in self.PRODUCTION_FILES:
            fpath = project_root / rel_path
            if not fpath.exists():
                continue
            content = fpath.read_text(encoding="utf-8")

            # Old-style canonical output pattern: creating workbook/vlm_parsed/ directly
            # (Note: references to "vlm_parsed" in comments/strings/symlinks are OK)
            # We check for directory CREATION patterns
            old_patterns = [
                re.compile(r'wb_dir\s*/\s*"vlm_parsed"'),
                re.compile(r'mkdir.*vlm_parsed'),
            ]
            for pat in old_patterns:
                matches = pat.findall(content)
                assert not matches, (
                    f"{rel_path} contains old-style output creation: {matches}"
                )

    def test_deprecated_scripts_marked(self):
        """Deprecated scripts exist and contain old-style output."""
        project_root = Path(__file__).resolve().parent.parent

        for rel_path in self.DEPRECATED_SCRIPTS:
            fpath = project_root / rel_path
            if not fpath.exists():
                continue
            content = fpath.read_text(encoding="utf-8")
            # These should contain old-style patterns (confirming classification)
            assert "vlm_parsed" in content, (
                f"{rel_path} doesn't look like a deprecated old-style script"
            )


# ─────────────────────────────────────────────────────────────────────────────
# Test 8: Import verification
# ─────────────────────────────────────────────────────────────────────────────


class TestImports:
    def test_output_writer_importable(self):
        """UnifiedOutputWriter can be imported without errors."""
        from hermes_bedrock_agent.parsing.output_writer import (
            UnifiedOutputWriter,
            WorkbookPaths,
            WorkbookResult,
        )
        assert UnifiedOutputWriter is not None
        assert WorkbookPaths is not None
        assert WorkbookResult is not None

    def test_orchestrator_importable(self):
        """Orchestrator functions can be imported."""
        from hermes_bedrock_agent.parsing.orchestrator import (
            run_project_parsing,
            save_parsing_manifest,
        )
        assert run_project_parsing is not None
        assert save_parsing_manifest is not None
